# Generated by Django 3.1.8 on 2023-09-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_create_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-id']},
        ),
    ]
